definitions:
  agent.AgentInfo:
    properties:
      created_at:
        type: string
      email:
        type: string
      hostname:
        type: string
      id:
        type: string
      ip_address:
        type: string
      kernel_version:
        type: string
      os_version:
        type: string
    type: object
  server.AuthTokenData:
    properties:
      createdAt:
        type: string
      id:
        type: string
      maskedToken:
        type: string
    type: object
  server.chatRequest:
    properties:
      chat:
        type: string
      history:
        items:
          $ref: '#/definitions/server.content'
        type: array
    type: object
  server.content:
    properties:
      parts:
        items:
          $ref: '#/definitions/server.part'
        type: array
      role:
        type: string
    type: object
  server.part:
    properties:
      text:
        type: string
    type: object
info:
  contact:
    email: harsha@harshanu.space
    name: API Support
    url: https://nannyai.harshanu.space/support
  license:
    name: GNU General Public License v3.0
    url: https://www.gnu.org/licenses/gpl-3.0.html
paths:
  /api/agent-info:
    post:
      consumes:
      - application/json
      description: Ingest agent information
      parameters:
      - description: Agent Information
        in: body
        name: agentInfo
        required: true
        schema:
          $ref: '#/definitions/agent.AgentInfo'
      produces:
      - application/json
      responses:
        "201":
          description: Agent info saved successfully
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request payload
          schema:
            type: string
        "401":
          description: User not authenticated
          schema:
            type: string
        "500":
          description: Failed to save agent info
          schema:
            type: string
      summary: Ingest agent information
      tags:
      - agent-info
  /api/agent-info/{id}:
    get:
      description: Retrieves agent information by ID
      parameters:
      - description: Agent ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved agent info
          schema:
            $ref: '#/definitions/agent.AgentInfo'
        "400":
          description: Invalid ID format
          schema:
            type: string
        "401":
          description: User not authenticated
          schema:
            type: string
        "404":
          description: Agent info not found
          schema:
            type: string
        "500":
          description: Failed to retrieve agent info
          schema:
            type: string
      summary: Get agent info by ID
      tags:
      - agent-info
  /api/auth-token/{id}:
    delete:
      description: Deletes a specific auth token by ID.
      parameters:
      - description: Token ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Auth token deleted successfully
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid token ID format or Token ID is required
          schema:
            type: string
        "500":
          description: Failed to delete auth token
          schema:
            type: string
      summary: Delete an auth token
      tags:
      - auth-tokens
  /api/auth-tokens:
    get:
      description: Retrieves all auth tokens for the authenticated user.
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved auth tokens
          schema:
            items:
              $ref: '#/definitions/server.AuthTokenData'
            type: array
        "401":
          description: User not authenticated
          schema:
            type: string
        "500":
          description: Failed to retrieve auth tokens
          schema:
            type: string
      summary: Get all auth tokens
      tags:
      - auth-tokens
  /auth-tokens:
    get:
      description: Serves the auth tokens page.
      produces:
      - text/html
      responses:
        "200":
          description: Successfully served auth tokens page
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get auth tokens page
      tags:
      - auth-tokens
  /chat:
    post:
      consumes:
      - application/json
      description: Chat with the model
      parameters:
      - description: Chat request
        in: body
        name: chat
        required: true
        schema:
          $ref: '#/definitions/server.chatRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Chat with the model
      tags:
      - chat
  /status:
    get:
      consumes:
      - application/json
      description: Status of the API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Status of the API
      tags:
      - status
  /user-auth-token:
    get:
      description: Fetch user info from auth token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Fetch user info from auth token
      tags:
      - auth-tokens
swagger: "2.0"
