name: CD

on:
  push:
    branches:
      - fix-cd ## temp only for testing
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Build binary
      run: |
        GOARCH=arm64 go build -o nannyapi ./cmd/main.go

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: nannyapi
        path: |
          nannyapi
          static/
  
  deploy:
    runs-on: [self-hosted, linux, ARM64]
    needs: build

    steps:
    - name: Download binary
      uses: actions/download-artifact@v4
      with:
        name: nannyapi
        path: nannyapi
        
    - name: Clean work directory except env.conf
      run: |
        find /opt/nannyapi-workdir/ -mindepth 1 -not -name 'env.conf' -delete
    
    - name: Deploy binary and static files
      run: |
        mv /home/ubuntu/actions-runner/_work/nannyapi/nannyapi/nannyapi/* /opt/nannyapi-workdir/
        chmod +x /opt/nannyapi-workdir/nannyapi

    - name: Restart nannyapi service
      run: |
        sudo systemctl restart nannyapi.service