name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Install dependencies
      run: go mod tidy
    
    - name: Run all tests except internal/server
      run: |
        packages=$(go list ./... | grep -v '/internal/server')
        if [[ -n "$packages" ]]; then
          go test $packages -v -count=1
        else
          echo "No packages found outside of internal/server to test."
        fi
      env:
        GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
        GH_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        NANNY_ENCRYPTION_KEY: ${{ secrets.NANNY_ENCRYPTION_KEY }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}


    - name: Run tests in internal/server
      run: go test ./internal/server -v -count=1
      env:
        GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
        GH_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        NANNY_ENCRYPTION_KEY: ${{ secrets.NANNY_ENCRYPTION_KEY }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
